import "~/styles/globals.css";

import { Inter } from "next/font/google";


import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { Navbar } from "./_components/Navbar";
import { Toaster } from "../components/ui/toaster"
import { SidebarContextProvider } from "~/context/SidebarContext";
import TaskSideBar from "./_components/TaskSidebar";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable} relative`}>
          <TRPCReactProvider>
            <SidebarContextProvider>
              <Navbar />
                {children}
              <Toaster/>
              <TaskSideBar/>
            </SidebarContextProvider>
          </TRPCReactProvider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
